package com.example.KFCC_Backend.Enum;

public enum PublicityApplicationStatus {
    DRAFT,
    NOT_SUBMITTED,
    SUBMITTED,

    STAFF_APPROVED,
    STAFF_REMARKED,
    STAFF_REJECTED,

    VP_APPROVED,
    VP_REMARKED,
    VP_REJECTED,

    SECRETARY_APPROVED,
    SECRETARY_REMARKED,
    SECRETARY_REJECTED,

    FINAL_APPROVED,
    MANAGER_REJECTED,
}
