package com.example.KFCC_Backend.Enum;

public enum TitleApplicationStatus {
    DRAFT,
    SUBMITTED,
    STAFF_ACCEPTED,
    STAFF_REJECTED,
    TITLE_COMMITTEE_LEADER_REJECTED,
    TITLE_COMMITTEE_ACCEPTED,
    EC_COMMITTEE_REVIEW,
    APPROVED,
    REJECTED,
    REMARKED
}
