package com.example.KFCC_Backend.Enum;

public enum TitleApplicationStatus {
    DRAFT,
    SUBMITTED,
    STAFF_APPROVED,
    STAFF_REJECTED,
    TITLE_COMMITTEE_REJECTED,
    TITLE_COMMITTEE_APPROVED,
    EC_COMMITTEE_REJECTED,
    EC_COMMITTEE_HOLD,
    FINAL_APPROVED,
    REJECTED,
    REMARKED;
}
